apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer    
  ports:
    - nodePort: 30000
      port: 8081
      protocol: TCP
      targetPort: 8081
